//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTM_Web_App.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTM_Web_App.Server.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Best regards, MTM.
        /// </summary>
        internal static string BestRegards {
            get {
                return ResourceManager.GetString("BestRegards", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check in.
        /// </summary>
        internal static string Check_in {
            get {
                return ResourceManager.GetString("Check in", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check out.
        /// </summary>
        internal static string Check_out {
            get {
                return ResourceManager.GetString("Check out", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Current restaurant name cannot be empty..
        /// </summary>
        internal static string Current_restaurant_name_cannot_be_empty_ {
            get {
                return ResourceManager.GetString("Current restaurant name cannot be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deleted!.
        /// </summary>
        internal static string Deleted_ {
            get {
                return ResourceManager.GetString("Deleted!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Email already exist. Try logging in..
        /// </summary>
        internal static string Email_already_exist__Try_logging_in_ {
            get {
                return ResourceManager.GetString("Email already exist. Try logging in.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error occurred. Please try again later..
        /// </summary>
        internal static string Error_occurred__Please_try_again_later_ {
            get {
                return ResourceManager.GetString("Error occurred. Please try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error retrieving OAuth token..
        /// </summary>
        internal static string Error_retrieving_OAuth_token_ {
            get {
                return ResourceManager.GetString("Error retrieving OAuth token.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File does not exist..
        /// </summary>
        internal static string File_does_not_exist_ {
            get {
                return ResourceManager.GetString("File does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;copy; 2025 MTM. All rights reserved..
        /// </summary>
        internal static string FooterMessage {
            get {
                return ResourceManager.GetString("FooterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Given currency is not yet supported..
        /// </summary>
        internal static string Given_currency_is_not_yet_supported_ {
            get {
                return ResourceManager.GetString("Given currency is not yet supported.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Given name is already taken..
        /// </summary>
        internal static string Given_name_is_already_taken_ {
            get {
                return ResourceManager.GetString("Given name is already taken.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Given restaurant does not exist..
        /// </summary>
        internal static string Given_restaurant_does_not_exist_ {
            get {
                return ResourceManager.GetString("Given restaurant does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hello, {0}.
        /// </summary>
        internal static string HelloUser {
            get {
                return ResourceManager.GetString("HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Here are the details of your reservation:.
        /// </summary>
        internal static string Here_are_the_details_of_your_reservation_ {
            get {
                return ResourceManager.GetString("Here are the details of your reservation:", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hotel added!.
        /// </summary>
        internal static string Hotel_added_ {
            get {
                return ResourceManager.GetString("Hotel added!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hotel deleted..
        /// </summary>
        internal static string Hotel_deleted {
            get {
                return ResourceManager.GetString("Hotel deleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hotel updated!.
        /// </summary>
        internal static string Hotel_updated_ {
            get {
                return ResourceManager.GetString("Hotel updated!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu If the problem persists, please contact us..
        /// </summary>
        internal static string If_the_problem_persists__please_contact_us_ {
            get {
                return ResourceManager.GetString("If the problem persists, please contact us.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu If you have any questions or need to make changes to your reservation, please do not hesitate to contact us..
        /// </summary>
        internal static string If_you_have_any_questions_or_need_to_make_changes_to_your_reservation__please_do_not_hesitate_to_contact_us_ {
            get {
                return ResourceManager.GetString("If you have any questions or need to make changes to your reservation, please do " +
                        "not hesitate to contact us.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu If you have any questions or need to update your reservation, feel free to reach out to us..
        /// </summary>
        internal static string If_you_have_any_questions_or_need_to_update_your_reservation__feel_free_to_reach_out_to_us_ {
            get {
                return ResourceManager.GetString("If you have any questions or need to update your reservation, feel free to reach " +
                        "out to us.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu If you didn&apos;t request this code, please ignore this email..
        /// </summary>
        internal static string IgnoreEmail {
            get {
                return ResourceManager.GetString("IgnoreEmail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Image added!.
        /// </summary>
        internal static string Image_added_ {
            get {
                return ResourceManager.GetString("Image added!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Image deleted!.
        /// </summary>
        internal static string Image_Deleted_ {
            get {
                return ResourceManager.GetString("Image Deleted!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Images added!.
        /// </summary>
        internal static string Images_added_ {
            get {
                return ResourceManager.GetString("Images added!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid date..
        /// </summary>
        internal static string Inavalid_date_ {
            get {
                return ResourceManager.GetString("Inavalid date.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Incorrect facilities..
        /// </summary>
        internal static string Incorrect_facilities_ {
            get {
                return ResourceManager.GetString("Incorrect facilities.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid check-in time format..
        /// </summary>
        internal static string Invalid_check_in_time_format_ {
            get {
                return ResourceManager.GetString("Invalid check-in time format.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid check-out time format..
        /// </summary>
        internal static string Invalid_check_out_time_format_ {
            get {
                return ResourceManager.GetString("Invalid check-out time format.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid closing time format..
        /// </summary>
        internal static string Invalid_closing_time_format_ {
            get {
                return ResourceManager.GetString("Invalid closing time format.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid credentials..
        /// </summary>
        internal static string Invalid_credentials_ {
            get {
                return ResourceManager.GetString("Invalid credentials.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid data..
        /// </summary>
        internal static string Invalid_data_ {
            get {
                return ResourceManager.GetString("Invalid data.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid email..
        /// </summary>
        internal static string Invalid_email_ {
            get {
                return ResourceManager.GetString("Invalid email.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid email address..
        /// </summary>
        internal static string Invalid_email_address_ {
            get {
                return ResourceManager.GetString("Invalid email address.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid file extension..
        /// </summary>
        internal static string Invalid_file_extension_ {
            get {
                return ResourceManager.GetString("Invalid file extension.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid image extension. Accepted formats are &quot;.png&quot; and &quot;.jpg&quot;..
        /// </summary>
        internal static string Invalid_image_extension__Accepted_formats_are__png_and__jpg_ {
            get {
                return ResourceManager.GetString("Invalid image extension. Accepted formats are .png and .jpg.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid opening time format..
        /// </summary>
        internal static string Invalid_opening_time_format_ {
            get {
                return ResourceManager.GetString("Invalid opening time format.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid request..
        /// </summary>
        internal static string Invalid_request_ {
            get {
                return ResourceManager.GetString("Invalid request.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid reservation end time format..
        /// </summary>
        internal static string Invalid_reservation_end_time_format_ {
            get {
                return ResourceManager.GetString("Invalid reservation end time format.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid reservation start time format..
        /// </summary>
        internal static string Invalid_reservation_start_time_format_ {
            get {
                return ResourceManager.GetString("Invalid reservation start time format.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid open times.
        /// </summary>
        internal static string InvalidOpenTimes {
            get {
                return ResourceManager.GetString("InvalidOpenTimes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Logged out!.
        /// </summary>
        internal static string Logged_out_successfully_ {
            get {
                return ResourceManager.GetString("Logged out successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login using Google and then set your password..
        /// </summary>
        internal static string Login_using_Google_and_then_set_your_password_ {
            get {
                return ResourceManager.GetString("Login using Google and then set your password.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing name..
        /// </summary>
        internal static string Missing_name {
            get {
                return ResourceManager.GetString("Missing name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing restaurant name..
        /// </summary>
        internal static string Missing_restaurant_name_ {
            get {
                return ResourceManager.GetString("Missing restaurant name.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No hotels..
        /// </summary>
        internal static string No_hotels_ {
            get {
                return ResourceManager.GetString("No hotels.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No hotels with specified filters..
        /// </summary>
        internal static string No_hotels_with_specified_filters_ {
            get {
                return ResourceManager.GetString("No hotels with specified filters.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No images added..
        /// </summary>
        internal static string No_images_added_ {
            get {
                return ResourceManager.GetString("No images added.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No logs..
        /// </summary>
        internal static string No_logs_ {
            get {
                return ResourceManager.GetString("No logs.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No owned restaurants..
        /// </summary>
        internal static string No_owned_restaurants_ {
            get {
                return ResourceManager.GetString("No owned restaurants.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No reservations..
        /// </summary>
        internal static string No_reservations_ {
            get {
                return ResourceManager.GetString("No reservations.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No restaurant with given name..
        /// </summary>
        internal static string No_restaurant_with_given_name_ {
            get {
                return ResourceManager.GetString("No restaurant with given name.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No restaurants..
        /// </summary>
        internal static string No_restaurants_ {
            get {
                return ResourceManager.GetString("No restaurants.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No restaurants with specified filters..
        /// </summary>
        internal static string No_restaurants_with_specified_filters_ {
            get {
                return ResourceManager.GetString("No restaurants with specified filters.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No results for given address..
        /// </summary>
        internal static string No_results_for_given_address_ {
            get {
                return ResourceManager.GetString("No results for given address.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of guests.
        /// </summary>
        internal static string Number_of_guests {
            get {
                return ResourceManager.GetString("Number of guests", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu One-Time Code has been sent..
        /// </summary>
        internal static string One_Time_Code_has_been_sent_ {
            get {
                return ResourceManager.GetString("One-Time Code has been sent.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your one-time code.
        /// </summary>
        internal static string OTCEmailTitle {
            get {
                return ResourceManager.GetString("OTCEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Request was cancelled..
        /// </summary>
        internal static string Request_was_cancelled_ {
            get {
                return ResourceManager.GetString("Request was cancelled.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reservation.
        /// </summary>
        internal static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reservation Details.
        /// </summary>
        internal static string Reservation_Details {
            get {
                return ResourceManager.GetString("Reservation Details", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reservation number:.
        /// </summary>
        internal static string Reservation_number_ {
            get {
                return ResourceManager.GetString("Reservation number:", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reservation placed!.
        /// </summary>
        internal static string Reservation_Placed_ {
            get {
                return ResourceManager.GetString("Reservation Placed!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reservation QR code:.
        /// </summary>
        internal static string Reservation_QR_code_ {
            get {
                return ResourceManager.GetString("Reservation QR code:", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reservation Reminder.
        /// </summary>
        internal static string Reservation_Reminder {
            get {
                return ResourceManager.GetString("Reservation Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restaurant added!.
        /// </summary>
        internal static string Restaurant_added_ {
            get {
                return ResourceManager.GetString("Restaurant added!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restaurant deleted..
        /// </summary>
        internal static string Restaurant_deleted {
            get {
                return ResourceManager.GetString("Restaurant deleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restaurant updated!.
        /// </summary>
        internal static string Restaurant_updated_ {
            get {
                return ResourceManager.GetString("Restaurant updated!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Safe travels, and we look forward to welcoming you tomorrow!.
        /// </summary>
        internal static string Safe_travels__and_we_look_forward_to_welcoming_you_tomorrow_ {
            get {
                return ResourceManager.GetString("Safe travels, and we look forward to welcoming you tomorrow!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Something went wrong. Try again later..
        /// </summary>
        internal static string Something_went_wrong__Try_again_later_ {
            get {
                return ResourceManager.GetString("Something went wrong. Try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Specified hotel does not exist..
        /// </summary>
        internal static string Specified_hotel_does_not_exist_ {
            get {
                return ResourceManager.GetString("Specified hotel does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Specified restaraurant does not exist..
        /// </summary>
        internal static string Specified_restaraurant_does_not_exist_ {
            get {
                return ResourceManager.GetString("Specified restaraurant does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Specified room does not exist..
        /// </summary>
        internal static string Specified_room_does_not_exist_ {
            get {
                return ResourceManager.GetString("Specified room does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Thank you for your reservation at.
        /// </summary>
        internal static string Thank_you_for_your_reservation_at {
            get {
                return ResourceManager.GetString("Thank you for your reservation at", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This code is valid for the next 10 minutes. Please do not share it with anyone..
        /// </summary>
        internal static string This_code_is_valid_for_the_next_10_minutes__Please_do_not_share_it_with_anyone_ {
            get {
                return ResourceManager.GetString("This code is valid for the next 10 minutes. Please do not share it with anyone.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This is a friendly reminder about your upcoming reservation at.
        /// </summary>
        internal static string This_is_a_friendly_reminder_about_your_upcoming_reservation_at {
            get {
                return ResourceManager.GetString("This is a friendly reminder about your upcoming reservation at", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User updated..
        /// </summary>
        internal static string User_Updated_ {
            get {
                return ResourceManager.GetString("User Updated.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To complete your verification process, please use the following one-time code:.
        /// </summary>
        internal static string VerificationMessage {
            get {
                return ResourceManager.GetString("VerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Verify your email address first..
        /// </summary>
        internal static string Verify_your_email_address_first_ {
            get {
                return ResourceManager.GetString("Verify your email address first.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We look forward to welcoming you!.
        /// </summary>
        internal static string We_look_forward_to_welcoming_you_ {
            get {
                return ResourceManager.GetString("We look forward to welcoming you!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You didn&apos;t provided any profile picture to add..
        /// </summary>
        internal static string You_didn_t_provided_any_profile_picture_to_add_ {
            get {
                return ResourceManager.GetString("You didn\'t provided any profile picture to add.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You do not have permission to do that..
        /// </summary>
        internal static string You_do_not_have_permission_to_do_that_ {
            get {
                return ResourceManager.GetString("You do not have permission to do that.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You do not have profile picture..
        /// </summary>
        internal static string You_do_not_have_profile_picture_ {
            get {
                return ResourceManager.GetString("You do not have profile picture.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You do not own hotel with given name..
        /// </summary>
        internal static string You_do_not_own_hotel_with_given_name_ {
            get {
                return ResourceManager.GetString("You do not own hotel with given name.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You do not own restaurant with given name..
        /// </summary>
        internal static string You_do_not_own_restaurant_with_given_name_ {
            get {
                return ResourceManager.GetString("You do not own restaurant with given name.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu One-time code is valid!.
        /// </summary>
        internal static string Your_email_address_has_been_verified_ {
            get {
                return ResourceManager.GetString("Your email address has been verified!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your email has been already verified..
        /// </summary>
        internal static string Your_email_has_been_already_verified_ {
            get {
                return ResourceManager.GetString("Your email has been already verified.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your One-Time Code is invalid.
        /// </summary>
        internal static string Your_One_Time_Code_is_invalid_ {
            get {
                return ResourceManager.GetString("Your One-Time Code is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your profie picture comes from Google link..
        /// </summary>
        internal static string Your_profie_picture_comes_from_Google_link_ {
            get {
                return ResourceManager.GetString("Your profie picture comes from Google link.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your reservation - .
        /// </summary>
        internal static string Your_reservation {
            get {
                return ResourceManager.GetString("Your reservation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your reservation details are as follows:.
        /// </summary>
        internal static string Your_reservation_details_are_as_follows_ {
            get {
                return ResourceManager.GetString("Your reservation details are as follows:", resourceCulture);
            }
        }
    }
}
