import LocalizedStrings from 'react-localization';

export const translations = new LocalizedStrings({
    en: {
        //Navbar.jsx
        account: "Account",
        reservations: "Reservations",
        logout: "Logout",
        login: "Log In",
        closeMenu: "Close menu",
        openMenu: "Open menu",
        mtm: "MTM",
        homePage: "Home Page",
        hotels: "Hotels",
        restaurants: "Restaurants",
        map: "Map",
        changeTheme: "Change theme",
        title: "{0} | MTM Project",
        typeToSearch: "Type to search...",
        search: "Search",
        searchFilter: "Search filter: {0}",
        loading: "Loading...",
        name: "Name",
        address: "Address",
        giveAddress: "Type address",
        description: "Description",
        searchedInCity: "Searched in city: {0}",
        searched: "Searched: {0}",
        pageYoureTryingToGetIntoIsForLoggedOnlyUsers: "The page you are trying to access is intended for logged in users.",
        error: "Error {0}",
        unauthorized: "Unauthorized",
        searchedRestaurantIs: "Searched restaurant is: {0}",
        pageYoureTryingToGetIntoDoesNotExist: "The page you are trying to reach does not exist. Sorry.",
        notFound: "Not Found",
        searchedHotelIs: "Searched hotel is: {0}",
        reserveByType: "Reserve by object type",
        house: "House",
        apartment: "Apartment",
        recommendedCusines: "Recommended cusines",
        signIn: "Logging In",
        continueUsingGoogle: "Continue with Google",
        or: "or",
        accountRecovery: "Account Recovery",
        questionsContactUs: "Have a question about your reservation? Call us. Customer service offices are open Monday through Friday from {0} to {1} at {2}.",
        about: "About us",
        colaboration: "Colaborate with us",
        app: "Mobile application",
        applicationUnavailablePC: "Application is unavaiable on PC yet.",
        applicationUnavailableIOS: "Application is unavaiable on iOS yet.",
        errorOccured: "Error occured.",
        loggedOut: "Logged out!",
        logingOut: "Logging out...",

        //Register Navbar
        passwordMustContain: "The password must consist of at least:",
        uppercase: "One uppercase letter",
        lowercase: "One lowercase letter",
        digit: "One digit",
        specialChar: "One special character",
        length: "8 characters",
        confirmPassword: "Confirm password",
        repeatPassword: "Repeat password",
        register: "Sign Up",
        changePasswordVisibilty: "Change password visibility",
        typePassword: "Enter password",
        password: "Password",
        next: "Next",
        typeCode: "Enter code",
        verificationCode: "Verification code",
        typeCodeSentToEmail: "Enter the code we sent to:",
        email: "Email",
        typeEmail: "Type your email",
        name: "Name",
        typeName: "Enter your name",
        joinUs: "JOIN US!",
        and: "and",
        regulations: "By continuing you accept our ",
        tos: "Terms of Use",
        tosAccusative: "Terms of Use",
        privacyPolicy: "Privacy Policy",
        privacyPolicyAccusative: "Privacy Policy",
        useOfCookies: "Use of cookies",
        useOfCookiesAccusative: "Use of cookies",
        alreadyHaveAnAccount: "Already have an account?",
        giveValidName: "Please enter your name",
        giveValidEmail: "Please enter a valid email",
        giveValidCode: "Please enter valid one-time code",
        giveValidPassword: "Please enter a password meeting requirements",
        givePassword: "Please enter your password",
        giveValidConfirmPassword: "Please enter password matching previous one",
        loginError: "Given credentials are invalid",
        errorBoundary: "Oops! Something went wrong!",
        sorry: "Sorry.",
        back: "Back",
        dontHaveAccount: "Don't have an account?",
        forgottenPassword: "Forgot your password?",
        sendCode: "Send one-time code",
        resetPassword: "Reset password",
        resetingPasswordStep: "Reseting password - Step",

        FreeWiFi: "Free WiFi",
        FreeParking: "Free parking",
        PaidParking: "Paid parking",
        AirConditioning: "Air conditioning",
        Heating: "Heating",
        Elevator: "Elevator",
        WheelchairAccessible: "Wheelchair accessible",
        NonSmoking: "Non smoking room",
        Smoking: "Smoking room",
        PetFriendly: "Pet friendly",
        Kitchen: "Kitchen",
        PrivateBathroom: "Private bathroom",
        WashingMachine: "Washing machine",
        Dryer: "Dryer",
        Iron: "Iron",
        HairDryer: "Hair dryer",
        Pool: "Pool",
        HotTub: "Hot tub",
        Sauna: "Sauna",
        FitnessCenter: "Fitness center",
        Spa: "Spa",
        MassageService: "Massage service",
        GameRoom: "Game room",
        Playground: "Playground",
        Library: "Library",
        Garden: "Garden",
        Terrace: "Terrace",
        BarbecueFacilities: "Barbecue facilities",
        TennisCourt: "Tennis court",
        GolfCourse: "Golf course",
        WaterSportsFacilities: "Water sports facilities",
        SkiStorage: "Ski storage",
        SkiInSkiOutAccess: "Ski in ski out access",
        HikingTrails: "Hiking trails",
        BicycleRental: "Bicycle rental",
        HorseRiding: "Horse riding",
        BowlingAlley: "Bowling alley",
        AirportShuttle: "Airport shuttle",
        CarRental: "Car rental",
        ElectricVehicleCharging: "Electric vehicle charging",
        RoomService: "Room service",
        MiniBar: "Mini bar",
        CoffeeMaker: "Coffee maker",
        InRoomSafe: "In room safe",
        FlatScreenTV: "Flatscreen TV",
        Balcony: "Balcony",
        OceanView: "Ocean view",
        MountainView: "Mountain view",
        BlackoutCurtains: "Blackout curtains",
        PremiumBedding: "Premium bedding",
        Restaurant: "Restaurant",
        Bar: "Bar",
        BreakfastIncluded: "Breakfast included",
        Kitchenette: "Kitchenette",
        VendingMachine: "Vending machine",
        ConciergeService: "Concierge service",
        Housekeeping: "Housekeeping",
        LaundryService: "Laundry service",
        BabysittingService: "Babysitting service",
        LuggageStorage: "Luggage storage",
        CurrencyExchange: "Currency exchange",
        ATMOnSite: "ATM on site",
        TourDesk: "Tour desk",
        TicketService: "Ticket service",
        BusinessCenter: "Business center",
        MeetingRooms: "Meeting rooms",
        HypoallergenicRooms: "Hypoallergenic rooms",
        FamilyRooms: "Family rooms",
        FreeHighSpeedInternet: "Free high speed internet",
        SatelliteTV: "Satellite TV",
        StreamingServiceAccess: "Streaming service access",
        SmartHomeFeatures: "Smart home features",
        USBChargingPorts: "USB charging ports",
        MultilingualStaff: "Multilingual staff",
        Fireplace: "Fireplace",
        SelfCheckIn: "Self check in",
        EcoFriendly: "Eco friendly",

        POST: "Add",
        GET: "Get",
        PUT: "Update",
        DELETE: "Delete",
        logs: "logs",
        user: "user",
        table: "table",
        room: "room",
        hotel: "hotel",
        ownedRestaurants: "owned restaurants",
        restaurant: "restaurant",
        freeName: "free name",
        hotelRes: "hotel reservations",
        restaurantRes: "restaurant reservations",
        restaurantRating: "restaurant rating",
        hotelRating: "hotel rating",
        addresses: "addresses",
        ownedHotels: "owned hotels",
        Login: "Login",
        googleLogin: "Google login",
        googleRegister: "Google sign Up",
        Register: "Register",
        OTPchecked: "OTP code check",
        hotelImage: "hotel image",
        userImage: "user image",
        roomImage: "room image",
        restaurantImage: "restaurant image",
        tableImage: "table image",

        Logs: "Logs",
        Edit: "Edit",
        Deleting: "Deleting",
        Delete: "Delete",

        pln: "Polish Zloty New",
        gbp: "Great Britain Pound",
        eur: "Euro",
        usd: "United States Dollar",
        cad: "Canadian Dollar",
        aud: "Australian Dollar",
        jpy: "Japanese Yen",
        inr: "Indian Rupee",
        nzd: "New Zealand Dollar",
        chf: "Swiss Franc",
        selectCurrency: "Select currency",
        polish: "Polish",
        english: "English",
        city: "City",
        typeCity: "Type city",
        dateRange: "Date range",
        date: "Date",
        nextWeek: "Next week",
        nextWeekend: "Next weekend",
        priceRange: "Price range",
        objType: "Object type",
        amenities: "Amenities",
        confirm: "Confirm",
        guestRating: "Guest rating",
        from: "From",
        to: "To",
        filters: "Filters",
        seeHotel: "See hotel",
        reservationNumber: "Reservation number",
        numberOfPeople: "Number of people",
        total: "Total",
        rooms: "Rooms",
        basicInfo: "Basic info",
        addInfo: "Additional information",
        images: "Images",
        hotelName: "Hotel name",
        typeHotelName: "Type hotel name",
        hotelDesc: "Hotel description",
        typeHotelDesc: "Type hotel description",
        hotelCurr: "Hotel currency",
        selectType: "Select object type",
        type: "Object type",
        facilities: "Amenities",
        selectFacilities: "Select amenities",
        checkIn: "Check in",
        checkOut: "Check out",
        save: "Save",
        continue: "Continue",
        selectThisPlace: "Select this place",
        roomName: "Room name",
        typeRoomName: "Type room name",
        roomDesc: "Room descriptiom",
        typeRoomDescription: "Type room description",
        roomPrice: "Room price",
        typeRoomPrice: "Type room price",
        numberOfGivenRooms: "Number of rooms",
        typeNumberOfGivenRooms: "Type number of rooms in this type",
        maxPeople: "Maximum number of people",
        typeMaxPeople: "Type maximum number of people in room",
        addHotel: "Add hotel",
        addRestaurant: "Add restaurant",
        tables: "Tables",
        cuisines: "Cuisines",
        restaurantName: "Restaurant name",
        typeRestaurantName: "Type restaurant name",
        restaurantDesc: "Restaurant description",
        typeRestaurantDesc: "Type restaurant description",
        restaurantCurr: "Restaurant currency",
        selectCuisines: "Select cuisines",
        tableName: "Table name",
        typeTableName: "Type table name",
        tableDesc: "Table descriptiom",
        typeTableDescription: "Type table description",
        tablePrice: "Table price",
        typeTablePrice: "Type table price",
        numberOfGivenTables: "Number of tables",
        typeNumberOfGivenTables: "Type number of tables in this type",
        typeMaxPeopleT: "Type maximum number of people at the table",

        Polish: 'Polish',
        Italian: 'Italian',
        Chinese: 'Chinese',
        Indian: 'Indian',
        Mexican: 'Mexican',
        French: 'French',
        Japanese: 'Japanese',
        Thai: 'Thai',
        Spanish: 'Spanish',
        Greek: 'Greek',
        American: 'American',
        Moroccan: 'Moroccan',
        Lebanese: 'Lebanese',
        Brazilian: 'Brazilian',
        Turkish: 'Turkish',
        Russian: 'Russian',
        Indonesian: 'Indonesian',
        Vietnamese: 'Vietnamese',
        Korean: 'Korean',
        Ethiopian: 'Ethiopian',
        Filipino: 'Filipino',
        Malaysian: 'Malaysian',
        Scandinavian: 'Scandinavian',
        German: 'German',
        Dutch: 'Dutch',
        British: 'British',
        South_African: 'South African',
        Pakistani: 'Pakistani',
        Peruvian: 'Peruvian',
        Australian: 'Australian',
        Argentine: 'Argentine',
        Egyptian: 'Egyptian',
        Hungarian: 'Hungarian',
        Irish: 'Irish',
        Caribbean: 'Caribbean',
        Bangladeshi: 'Bangladeshi',
        Ukrainian: 'Ukrainian',
        Jewish: 'Jewish',
        Basque: 'Basque',
        Finnish: 'Finnish',
        Chilean: 'Chilean',
        Afghan: 'Afghan',
        Tibetan: 'Tibetan',
        Cambodian: 'Cambodian',
        Singaporean: 'Singaporean',
        Sri_Lankan: 'Sri Lankan',
        Icelandic: 'Icelandic',
        Scottish: 'Scottish',
        Maltese: 'Maltese',
        Belarusian: 'Belarusian',
        Welsh: 'Welsh',
        Zambian: 'Zambian',
        Omani: 'Omani',
        Kuwaiti: 'Kuwaiti',
        Syrian: 'Syrian',
        Albanian: 'Albanian',
        Bantu: 'Bantu',
        Hawaiian: 'Hawaiian',
        Uzbek: 'Uzbek',
        Azerbaijani: 'Azerbaijani',
        Georgian: 'Georgian',
        Estonian: 'Estonian',
        Latvian: 'Latvian',
        Lithuanian: 'Lithuanian',
        Bhutanese: 'Bhutanese',
        Samoan: 'Samoan',
        Tongan: 'Tongan',
        Fijian: 'Fijian',
        Marshallese: 'Marshallese',
        Papua_New_Guinean: 'Papua New Guinean',
        Micronesian: 'Micronesian',
        Greenlandic: 'Greenlandic',
        Andorran: 'Andorran',
        Surinamese: 'Surinamese',
        Guyanese: 'Guyanese',
        Trinidadian: 'Trinidadian',
        Mauritian: 'Mauritian',
        Seychellois: 'Seychellois',
        Tatar: 'Tatar',
        Chuvash: 'Chuvash',
        Yakut: 'Yakut',
        Buryat: 'Buryat',
        Breton: 'Breton',
        Corsican: 'Corsican',
        Catalan: 'Catalan',
        Walloon: 'Walloon',
        Aragonese: 'Aragonese',
        Galician: 'Galician',
        Moldovan: 'Moldovan',
        Panamanian: 'Panamanian',
        Salvadoran: 'Salvadoran',
        Nicaraguan: 'Nicaraguan',
        Costa_Rican: 'Costa_Rican',
        Dominican: 'Dominican',
        Paraguayan: 'Paraguayan',
        Uruguayan: 'Uruguayan',
        Ecuadorean: 'Ecuadorean',
        Bolivian: 'Bolivian',
        Venezuelan: 'Venezuelan',
        Haitian: 'Haitian',
        Jamaican: 'Jamaican',
        Northern_Irish: 'Northern Irish',
        Turkish_Cypriot: 'Turkish Cypriot',
        Greek_Cypriot: 'Greek Cypriot',
        Monday: "Monday",
        Tuesday: "Tuesday",
        Wednesday: "Wednesday",
        Thursday: "Thursday",
        Friday: "Friday",
        Saturday: "Saturday",
        Sunday: "Sunday",
        ReservationNumber: "Reservation number",
        seeReservation: "See your reservation",
        yourHotelRes: "Your hotels reservations",
        yourRestaurantRes: "Your restaurants reservations",

        selectDayOfWeek: "Select day of week",
        dayOfWeek: "Day of week",
        areYouSure: "Are you sure? This action is irreversible.",
        spotsCount: "Number of places",
        reservationsCost: "Reservation price",
        nightCost: "Price per night",
        addRooms: "Add rooms",
        addTables: "Add tables",
        selectReservationDate: "Select reservatoin date",
        reserve: "Reserve",
        noReservations: "No reservations",
        cancel: "Cancel",
        reservationDeleted: "Reservation deleted.",
        deletingError: "Error occured while deleting.",

    },
    pl: {
        account: "Konto",
        reservations: "Rezerwacje",
        logout: "Wyloguj",
        closeMenu: "Zamknij menu",
        openMenu: "Otwórz menu",
        mtm: "MTM",
        homePage: "Strona domowa",
        hotels: "Hotele",
        restaurants: "Restauracje",
        map: "Mapa",
        changeTheme: "Zmień motyw",
        title: "{0} | MTM Project",
        typeToSearch: "Wpisz aby wyszukać...",
        search: "Szukaj",
        searchFilter: "Filtr wyszukiwania: {0}",
        loading: "Ładowanie...",
        name: "Nazwa",
        address: "Adres",
        giveAddress: "Podaj adres",
        description: "Opis",
        searchedInCity: "Wyszukano w mieście: {0}",
        searched: "Wyszukano: {0}",
        pageYoureTryingToGetIntoIsForLoggedOnlyUsers: "Strona, na którą próbujesz się dostać przeznaczona jest dla zalogowanych użytkowników.",
        error: "Błąd {0}",
        unauthorized: "Brak dostępu",
        searchedRestaurantIs: "Wyszukana restauracja to: {0}",
        pageYoureTryingToGetIntoDoesNotExist: "Strona, którą próbujesz wyszukać nie istnieje. Przepraszamy.",
        notFound: "Nie znaleziono",
        searchedHotelIs: "Wyszukany hotel to: {0}",
        reserveByType: "Zarezerwuj według rodzaju obiektu",
        house: "Dom",
        apartment: "Apartament",
        recommendedCusines: "Rekomendowane kuchnie",
        asian: "Azjatycka",
        american: "Amerykańska",
        italian: "Włoska",
        fillAllFields: "Proszę wypełnić wszystkie pola.",
        signIn: "Logowanie",
        continueUsingGoogle: "Kontynuuj przez Google",
        or: "lub",
        accountRecovery: "Przywracanie dostępu do konta",
        questionsContactUs: "Masz pytanie odnośnie rezerwacji? Zadzwoń do nas. Biura obsługi klienta są czynne od poniedziałku do piątku w godz. {0} - {1} pod numerem tel. {2}.",
        about: "O nas",
        colaboration: "Współpracuj z nami",
        app: "Aplikacja mobilna",
        applicationUnavailablePC: "Aplikacja nie jest jeszcze dostępna na komputery.",
        applicationUnavailableIOS: "Aplikacja nie jest jeszcze dostępna na systemy iOS.",
        errorOccured: "Wystąpił błąd.",
        loggedOut: "Wylogowano!",
        logingOut: "Wylogowywanie...",

        //Register Navbar
        passwordMustContain: "Hasło musi składać się co najmniej z:",
        uppercase: "Jednej wielkiej litery",
        lowercase: "Jednej małej litery",
        digit: "Jednej cyfry",
        specialChar: "Jednego znaku specjalnego",
        length: "8 znaków",
        confirmPassword: "Potwierdź hasło",
        repeatPassword: "Powtórz hasło",
        register: "Zarejestruj się",
        changePasswordVisibilty: "Zmień widoczność hasła",
        typePassword: "Wpisz hasło",
        password: "Hasło",
        next: "Dalej",
        typeCode: "Wpisz kod",
        verificationCode: "Kod weryfikacyjny",
        typeCodeSentToEmail: "Wpisz kod, który wysłaliśmy na adres:",
        email: "Email",
        typeEmail: "Wpisz swój email",
        name: "Imię i nazwisko",
        typeName: "Wpisz swoje imię i nazwisko",
        joinUs: "DOŁĄCZ DO NAS!",
        and: "i",
        regulations: "Kontynuując akceptujesz nasze ",
        tos: "Zasady użytkowania",
        tosAccusative: "Zasady użytkowania",
        privacyPolicy: "Polityka prywatności",
        privacyPolicyAccusative: "Politykę prywatności",
        useOfCookies: "Korzystanie z plików cookies",
        useOfCookiesAccusative: "Korzystanie z plików cookies",
        alreadyHaveAnAccount: "Masz już konto?",
        login: "Zaloguj się",
        giveValidName: "Proszę podać imię i nazwisko",
        giveValidEmail: "Podany adres email jest niepoprawny",
        giveValidCode: "Podany kod weryfikacyjny jest niepoprawny",
        giveValidPassword: "Proszę podać hasło spełniające kryteria bezpieczeństwa",
        givePassword: "Proszę podać hasło",
        giveValidConfirmPassword: "Hasła się nie zgadzają",
        loginError: "Podane dane logowania są niepoprawne",
        errorBoundary: "Oops! Coś poszło nie tak!",
        sorry: "Przepraszamy.",
        back: "Wstecz",
        dontHaveAccount: "Nie masz konta?",
        forgottenPassword: "Zapomniane hasło?",
        sendCode: "Wyślij kod",
        resetPassword: "Zresetuj hasło",
        resetingPasswordStep: "Resetowanie hasła - Krok",

        FreeWiFi: "Bezpłatne WiFi",
        FreeParking: "Bezpłatny parking",
        PaidParking: "Płatny parking",
        AirConditioning: "Klimatyzacja",
        Heating: "Ogrzewanie",
        Elevator: "Winda",
        WheelchairAccessible: "Dostęp dla wózków inwalidzkich",
        NonSmoking: "Pokój dla niepalących",
        Smoking: "Pokój dla palących",
        PetFriendly: "Przyjazny dla zwierząt",
        Kitchen: "Kuchnia",
        PrivateBathroom: "Prywatna łazienka",
        WashingMachine: "Pralka",
        Dryer: "Suszarka",
        Iron: "Żelazko",
        HairDryer: "Suszarka do włosów",
        Pool: "Basen",
        HotTub: "Wanna z hydromasażem",
        Sauna: "Sauna",
        FitnessCenter: "Centrum fitness",
        Spa: "Spa",
        MassageService: "Usługa masażu",
        GameRoom: "Pokój gier",
        Playground: "Plac zabaw",
        Library: "Biblioteka",
        Garden: "Ogród",
        Terrace: "Taras",
        BarbecueFacilities: "Udogodnienia do grillowania",
        TennisCourt: "Kort tenisowy",
        GolfCourse: "Pole golfowe",
        WaterSportsFacilities: "Sporty wodne",
        SkiStorage: "Przechowalnia nart",
        SkiInSkiOutAccess: "Dostęp do tras narciarskich",
        HikingTrails: "Szlaki turystyczne",
        BicycleRental: "Wypożyczalnia rowerów",
        HorseRiding: "Jazda konna",
        BowlingAlley: "Kręgielnia",
        AirportShuttle: "Transport lotniskowy",
        CarRental: "Wynajem samochodów",
        ElectricVehicleCharging: "Ładowanie pojazdów elektrycznych",
        RoomService: "Obsługa pokoju",
        MiniBar: "Mini bar",
        CoffeeMaker: "Ekspres do kawy",
        InRoomSafe: "Sejf w pokoju",
        FlatScreenTV: "Telewizor z płaskim ekranem",
        Balcony: "Balkon",
        OceanView: "Widok na morze",
        MountainView: "Widok na góry",
        BlackoutCurtains: "Zasłony zaciemniające",
        PremiumBedding: "Pościel premium",
        Restaurant: "Restauracja",
        Bar: "Bar",
        BreakfastIncluded: "Śniadanie wliczone w cenę",
        Kitchenette: "Aneks kuchenny",
        VendingMachine: "Automat z przekąskami",
        ConciergeService: "Usługi konsjerża",
        Housekeeping: "Sprzątanie",
        LaundryService: "Pralnia",
        BabysittingService: "Usługa opieki nad dziećmi",
        LuggageStorage: "Przechowalnia bagażu",
        CurrencyExchange: "Kantor wymiany walut",
        ATMOnSite: "Bankomat",
        TourDesk: "Biuro wycieczek",
        TicketService: "Usługa sprzedaży biletów",
        BusinessCenter: "Centrum biznesowe",
        MeetingRooms: "Sale konferencyjne",
        HypoallergenicRooms: "Pokoje dla alergików",
        FamilyRooms: "Pokoje rodzinne",
        FreeHighSpeedInternet: "Bezpłatne szybkie łącze internetowe",
        SatelliteTV: "Telewizja satelitarna",
        StreamingServiceAccess: "Dostęp do platform streamingowych",
        SmartHomeFeatures: "Funkcje inteligentnego domu",
        USBChargingPorts: "Porty ładowania USB",
        MultilingualStaff: "Wielojęzyczny personel",
        Fireplace: "Kominek",
        SelfCheckIn: "Samodzielne zameldowanie",
        EcoFriendly: "Przyjazny dla środowiska",

        POST: "Dodano",
        GET: "Zażądano",
        PUT: "Zaktualizowano",
        DELETE: "Usunięto",
        logs: "logów",
        user: "użytkownik",
        table: "stolik",
        room: "pokój",
        hotel: "hotel",
        ownedRestaurants: "posiadane restauracje",
        restaurant: "restaurację",
        freeName: "wolnej nazwy",
        hotelRes: "rezerwacje hotelowe",
        restaurantRes: "rezerwacje restauracji",
        restaurantRating: "ocene restauracji",
        hotelRating: "ocene hotelu",
        addresses: "adresy",
        ownedHotels: "posiadane hotele",
        Login: "Zalogowano",
        googleLogin: "Zalogowano za pomocą Google",
        googleRegister: "Zarejestrowano za pomocą Google",
        Register: "Zarejestrowano",
        OTPchecked: "Sprawdzono kod weryfikacyjny",
        hotelImage: "zdjęcie hotelu",
        userImage: "zdjęcie użytkownika",
        roomImage: "zdjęcie pokoju",
        restaurantImage: "zdjęcie restauracji",
        tableImage: "zdjęcie stolika",

        Logs: "Logi",
        Edit: "Edycja",
        Deleting: "Usuwanie",
        Delete: "Usuń",

        pln: "Polski Złoty",
        gbp: "Funt brytyjski",
        eur: "Euro",
        usd: "Dolar amerykański",
        cad: "Dolar kanadyjski",
        aud: "Dolar australijski",
        jpy: "Jen japoński",
        inr: "Rupia indyjska",
        nzd: "Dolar nowozelandzki",
        chf: "Frank szwajcarski",
        selectCurrency: "Wybierz walutę",
        polish: "Polski",
        english: "Angielski",
        city: "Miasto",
        typeCity: "Podaj miasto",
        dateRange: "Zakres dat",
        date: "Data",
        nextWeek: "Przyszły tydzień",
        nextWeekend: "Przyszły weekend",
        priceRange: "Zakres cen",
        objType: "Typ obiektu",
        amenities: "Udogodnienia",
        confirm: "Zatwierdź",
        guestRating: "Ocena gości",
        from: "Od",
        to: "Do",
        filters: "Filtry",
        seeHotel: "Zobacz hotel",
        reservationNumber: "Numer rezerwacji",
        numberOfPeople: "Liczba osób",
        total: "Suma",
        noSuchHotel: "Błąd: Strona obiektu nie istnieje",
        rooms: "Pokoje",
        basicInfo: "Podstawowe informacje",
        addInfo: "Dodatkowe informacje",
        images: "Obrazy",
        hotelName: "Nazwa hotelu",
        typeHotelName: "Podaj nazwę hotelu",
        hotelDesc: "Opis hotelu",
        typeHotelDesc: "Podaj opis hotelu",
        hotelCurr: "Waluta hotelu",
        selectType: "Wybierz typ",
        type: "Typ obiektu",
        facilities: "Udogodnienia",
        selectFacilities: "Wybierz udogodnienia",
        checkIn: "Zameldowanie",
        checkOut: "Wymeldowanie",
        save: "Zapisz",
        continue: "Kontynuuj",
        selectThisPlace: "Wybierz to miejsce",
        roomName: "Nazwa pokoju",
        typeRoomName: "Podaj nazwę pokoju",
        roomDesc: "Opis pokoju",
        typeRoomDescription: "Podaj opis pokoju",
        roomPrice: "Cena pokoju",
        typeRoomPrice: "Podaj cenę pokoju",
        numberOfGivenRooms: "Liczba pokoi",
        typeNumberOfGivenRooms: "Podaj liczbę pokoi tygo typu",
        maxPeople: "Maksymalna liczba osób",
        typeMaxPeople: "Podaj maksymalną liczbę osób w pokoju",
        addHotel: "Dodaj hotel",
        addRestaurant: "Dodaj restaurację",
        tables: "Stoły",
        cuisines: "Kuchnie",
        restaurantName: "Nazwa restauracji",
        typeRestaurantName: "Podaj nazwę restauracji",
        restaurantDesc: "Opis restauracji",
        typeRestaurantDesc: "Podaj opis restauracji",
        restaurantCurr: "Waluta restauracji",
        selectCuisines: "Wybierz kuchnię",
        tableName: "Nazwa stołu",
        typeTableName: "Podaj nazwę stołu",
        tableDesc: "Opis stołu",
        typeTableDescription: "Podaj opis stołu",
        tablePrice: "Cena rezerwacji stołu",
        typeTablePrice: "Podaj cenę rezerwacji",
        numberOfGivenTables: "Liczba stołów",
        typeNumberOfGivenTables: "Podaj liczbę stołów tego typu",
        typeMaxPeopleT: "Podaj maksymalną liczbę osób przy stole",
        Polish: 'Polska',
        Italian: 'Włoska',
        Chinese: 'Chińska',
        Indian: 'Indyjska',
        Mexican: 'Meksykańska',
        French: 'Francuska',
        Japanese: 'Japońska',
        Thai: 'Tajska',
        Spanish: 'Hiszpańska',
        Greek: 'Grecka',
        American: 'Amerykańska',
        Moroccan: 'Marokańska',
        Lebanese: 'Libańska',
        Brazilian: 'Brazylijska',
        Turkish: 'Turecka',
        Russian: 'Rosyjska',
        Indonesian: 'Indonezyjska',
        Vietnamese: 'Wietnamska',
        Korean: 'Koreańska',
        Ethiopian: 'Etiopska',
        Filipino: 'Filipińska',
        Malaysian: 'Malajska',
        Scandinavian: 'Skandynawska',
        German: 'Niemiecka',
        Dutch: 'Holenderska',
        British: 'Brytyjska',
        South_African: 'Południowoafrykańska',
        Pakistani: 'Pakistańska',
        Peruvian: 'Peruwiańska',
        Australian: 'Australijska',
        Argentine: 'Argentyńska',
        Egyptian: 'Egipska',
        Hungarian: 'Węgierska',
        Irish: 'Irlandzka',
        Caribbean: 'Karaibska',
        Bangladeshi: 'Banglijska',
        Ukrainian: 'Ukraińska',
        Jewish: 'Żydowska',
        Basque: 'Baskijska',
        Finnish: 'Fińska',
        Chilean: 'Chilijska',
        Afghan: 'Afgańska',
        Tibetan: 'Tybetańska',
        Cambodian: 'Kambodżańska',
        Singaporean: 'Singapurska',
        Sri_Lankan: 'Sri Lankijska',
        Icelandic: 'Islandzka',
        Scottish: 'Szkocka',
        Maltese: 'Maltańska',
        Belarusian: 'Białoruska',
        Welsh: 'Walijska',
        Zambian: 'Zambijska',
        Omani: 'Omańska',
        Kuwaiti: 'Kuwejcka',
        Syrian: 'Syryjska',
        Albanian: 'Albańska',
        Bantu: 'Bantu',
        Hawaiian: 'Hawajska',
        Uzbek: 'Uzbecka',
        Azerbaijani: 'Azerbejdżańska',
        Georgian: 'Gruzińska',
        Estonian: 'Estońska',
        Latvian: 'Łotewska',
        Lithuanian: 'Litewska',
        Bhutanese: 'Bhutańska',
        Samoan: 'Samoańska',
        Tongan: 'Tongijska',
        Fijian: 'Fidżyjska',
        Marshallese: 'Marszalska',
        Papua_New_Guinean: 'Papuańska',
        Micronesian: 'Mikronezyjska',
        Greenlandic: 'Grenlandzka',
        Andorran: 'Andorska',
        Surinamese: 'Surinamska',
        Guyanese: 'Gujanańska',
        Trinidadian: 'Trynidadzka',
        Mauritian: 'Maurytyjska',
        Seychellois: 'Seszelska',
        Tatar: 'Tatarska',
        Chuvash: 'Czuwaska',
        Yakut: 'Jakucka',
        Buryat: 'Buriacka',
        Breton: 'Bretońska',
        Corsican: 'Korsykańska',
        Catalan: 'Katalońska',
        Walloon: 'Walońska',
        Aragonese: 'Aragońska',
        Galician: 'Galicyjska',
        Moldovan: 'Mołdawska',
        Panamanian: 'Panamska',
        Salvadoran: 'Salwadorska',
        Nicaraguan: 'Nikaraguańska',
        Costa_Rican: 'Kostarykańska',
        Dominican: 'Dominikańska',
        Paraguayan: 'Paragwajska',
        Uruguayan: 'Urugwajska',
        Ecuadorean: 'Ekwadorska',
        Bolivian: 'Boliwijska',
        Venezuelan: 'Wenezuelska',
        Haitian: 'Haitańska',
        Jamaican: 'Jamajska',
        Northern_Irish: 'Irlandzkopółnocna',
        Turkish_Cypriot: 'Tureckocypryjska',
        Greek_Cypriot: 'Greckocypryjska',
        Monday: "Poniedziałek",
        Tuesday: "Wtorek",
        Wednesday: "Środa",
        Thursday: "Czwartek",
        Friday: "Piątek",
        Saturday: "Sobota",
        Sunday: "Niedziela",
        ReservationNumber: "Rezerwacja numer",
        seeReservation: "Zobacz swoją rezerwację",
        yourHotelRes: "Rezerwacje w twoich hotelach",
        yourRestaurantRes: "Rezerwacje w twoich restauracjach",

        selectDayOfWeek: "Wybierz dzień tygodnia",
        dayOfWeek: "Dzień tygodnia",
        areYouSure: "Na pewno? Ta akcja jest nieodwracalna.",
        spotsCount: "Ilość miejsc",
        reservationsCost: "Cena za rezerwację",
        nightCost: "Cena za noc",
        addRooms: "Dodaj pokoje",
        addTables: "Dodaj stoły",
        selectReservationDate: "Wybierz datę rezerwacji",
        reserve: "Zarezerwuj",
        noReservations: "Brak rezerwacji",
        cancel: "Anuluj",
        reservationDeleted: "Usunięto rezerwację.",
        deletingError: "Wystąpił błąd podczas usuwania.",
        notes: "Uwagi",

    },
});